# frontend/Dockerfile.dev
FROM node:22-alpine

# Enable pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Install dependencies first (caching optimization)
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# No need to copy the rest of the files (like server.js or src/ here because Docker Compose will use volumes to "bind mount" to sync live code.

EXPOSE 5173

# Start Vite and expose it to the network
CMD ["pnpm", "run", "dev", "--host"]